version: '3.1'

services:

  tofoo:
    image: mysql
    restart: always
    command: --default-time-zone='+03:00'
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306


  cache:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080